#!/bin/bash

pkg install python -y &>/dev/null
pkg install python-pip -y &>/dev/null
pip install psutil

cd /data/data/com.termux/files
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/BoxFartBox.tar.gz
tar -xf BoxFartBox.tar.gz -C /sdcard
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/optlibs.tar.xz
tar xf optlibs.tar.xz
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/optScripts.tar.xz
tar xf optScripts.tar.xz
cd /data/data/com.termux/files/usr/glibc/opt/Scripts
chmod +x b64 b64.py b64-start.py b64-virgl.py b64-virgl-mobox.py
cd /data/data/com.termux/files
rm -rf BoxFartBox.tar.gz
rm -rf optScripts.tar.xz
rm -rf optlibs.tar.xz
rm -rf $HOME/install
ln -sf /data/data/com.termux/files/usr/glibc/opt/Scripts/b64 /data/data/com.termux/files/usr/bin/b64
cd

echo "Done please exit termux first and rerun boxfartbox"
