#!/bin/bash

termux-setup-storage & sleep 4 &>/dev/null

while true; do
    if [ -d ~/storage/shared ]; then
        break
    else
        echo "Storage permission denied"
    fi
    sleep 3
done

echo "Installing termux packages"
apt-get clean
apt-get update >/dev/null 2>&1
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade >/dev/null 2>&1
pkg install x11-repo -y &>/dev/null
pkg install nano pulseaudio -y &>/dev/null
pkg install termux-am -y &>/dev/null
pkg install wget -y &>/dev/null
pkg install root-repo -y &>/dev/null
pkg install p7zip -y &>/dev/null
pkg install xorg-xrandr -y &>/dev/null
pkg install termux-x11-nightly -y &>/dev/null
apt install tur-repo -y &>/dev/null
apt install virglrenderer-android virglrenderer-mesa-zink -y &>/dev/null
pkg install python -y &>/dev/null
pkg install python-pip -y &>/dev/null
pip install psutil &>/dev/null

echo "Installing d64Box"
cd /data/data/com.termux/files
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/glibcfartbox.tar.xz
tar xf glibc.tar.xz
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/D64Box.tar.xz
tar -xf D64Box.tar.xz -C /sdcard
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/optapps.tar.xz
tar xf optapps.tar.xz
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/optlibs.tar.xz
tar xf optlibs.tar.xz
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/optprefix.tar.xz
tar xf optprefix.tar.xz
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/optScripts.tar.xz
tar xf optScripts.tar.xz
wget -q --show-progress https://github.com/mebabo1/menano/releases/download/Box/alsa.tar
tar xf alsa.tar
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/etcfonts.tar.gz
tar xf etcfonts.tar.gz
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/sharefont.tar.gz
tar xf sharefont.tar.gz
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/locale.7z
7z x -y locale.7z -o$PREFIX/glibc/lib/locale &>/dev/null
wget -q --show-progress https://github.com/Dark-Shiroe/testing/releases/download/boxfartbox/wine.tar.xz
tar -xf wine9.11.tar.xz -C $PREFIX/glibc/opt
cd /data/data/com.termux/files/usr/glibc/opt/Scripts
chmod +x d64 d64.py d64-start.py d64-cpu.py d64-virgl.py d64-virgl-mobox.py
cd /data/data/com.termux/files
rm -rf glibcfartbox.tar.xz
rm -rf D64Box.tar.xz
rm -rf optapps.tar.xz
rm -rf optlibs.tar.xz
rm -rf optprefix.tar.xz
rm -rf optScripts.tar.xz
rm -rf alsa.tar
rm -rf etcfonts.tar.gz
rm -rf sharefont.tar.gz
rm -rf locale.7z
rm -rf wine9.11.tar.xz
rm -rf $HOME/install02
ln -sf /data/data/com.termux/files/usr/glibc/opt/Scripts/d64 /data/data/com.termux/files/usr/bin/d64
cd

echo "To start d64Box run 'd64'"
