#!/bin/bash

pkg install termux-am -y
termux-setup-storage
apt-get clean
apt-get update
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgraded &>/dev/null
pkg install x11-repo -y &>/dev/null
pkg install pulseaudio -y &>/dev/null
pkg install xwayland -y &>/dev/null
pkg install wget -y &>/dev/null
pkg install tsu -y &>/dev/null
pkg install root-repo -y &>/dev/null
pkg install patchelf -y &>/dev/null
pkg install p7zip -y &>/dev/null
pkg install xorg-xrandr -y &>/dev/null
pkg install ncurses-utils -y &>/dev/null
pkg install hashdeep -y &>/dev/null
pkg install termux-x11-nightly -y &>/dev/null
pkg install python nmap vulkan-tools -y &>/dev/null
pkg install git python -y &>/dev/null
pkg install coreutils -y &>/dev/null
pkg install socat -y &>/dev/null
pip install objgraph &>/dev/null
pip install aiofiles &>/dev/null
pip install blessings &>/dev/null

wget https://github.com/mebabo1/menano/releases/download/Box/box64.tar.xz
tar xf box64.tar.xz
rm -rf box64.tar.xz


